stages:
  - build
  - deploy
  - deploy:PROD

build:
  stage: build
  script:
    - npm install
    - npx prettier --write .
    - npm install ajv --save-dev
    - npm run build
  only:
    - main
  artifacts:
    paths:
      - ./build

deploy:
  stage: deploy
  script:
    - cp -rf ./build/* /usr/share/nginx/school/
  only:
    - main

deploy:PROD:
  stage: deploy:PROD
  script:
    - cp -rf ./build/* /usr/share/nginx/prod_school
  when: manual
  only:
    - main
