stages:
  - build
  - deploy:test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npx prettier --write .
    - npm install ajv --save-dev
    - npm run build
  artifacts:
    paths:
      - ./build

deploy:test:
  stage: deploy:test
  script:
   	- cp -rf ./build/* /usr/share/nginx/prod_school
  when: manual
  only:
    - main

deploy:
  stage: deploy
  script:
    - cp -rf ./build/* /usr/share/nginx/school/
  only:
    - main
	