import i18n from "i18next";
import { initReactI18next } from "react-i18next";

// Configuration for i18next
i18n.use(initReactI18next).init({
  resources: {
    en: {
      translation: {
        Edit: "Edit",
        school_details: "School Details",
        school_name: "School Name",
        school_code: "School Code",
        fee_category: "Fee Category",
        create_fee_category: "Create Fee Category",
        edit_fee_category: "Edit Fee Category",
        existing_particulars: "Existing Particulars",
        add_new_particulars: "Add New Particulars",
        description: "Description",
        particular_name: "Particular Name",
        back: "Back",
        save: "Save",
        fee_amount_particular: "Fee Amount Particular",
        create_fee_amount_particular: "Create Fee Amount Particular",
        category_name: "Category Name",
        fee_particular: "Fee Particular",
        academic_year: "Academic Year",
        account: "Account",
        amount: "Amount",
        select_class_sections: "Select Class & Sections",
        select_student_category: "Select Student Category",
        class: "Class",
        section: "Section",
        select_students: "Select Students",
        fee_concession: "Fee Concession",
        create_fee_concession: "Create Fee Concession",
        show_data: "Show Data",
        manage_scheduled_concession: "Manage Scheduled Concession",
        concession_type: "Concession Type *",
        concession_name: "Concession Name",
        is_percent: "Is Percent",
        concession_amount: "Concession Amount",
        select_student: "Select Student",
        select_wings: "Select Wings",
        student_category: "Student Category",
        late_fee: "Late Fee",
        new_late_fee: "New Late Fee",
        create_late_fee: "Create Late Fee",
        fine_name: "Fine Name",
        late_fee_calculation_type: "Late Fee Calculation Type",
        days_after_due_date: "Days After Due Date",
        manage_late_fee: "Manage Late Fee",
        fee_schedule: "Fee Schedule",
        create_fee_schedule: "Create Fee Schedule",
        excess_fee: "Excess Fee",
        account_name: "Account Name",
        fine_particular: "Fine Particular",
        create_new_fine_particular: "Create New Fine Particular",
        create_fine_particular: "Create Fine Particular",
        student: "Student",
        excess_amount: "Excess Amount",
        select_payment_status: "Select Payment Status",
        add_amount: "Add Amount",
        total_amount: "Total Amount",
        fee_collection_name: "Fee Collection Name",
        start_date: "Start Date",
        end_date: "End Date",
        due_date: "Due Date",
        late_fine: "Late Fine",
        is_applicable: "Is Applicable",
        fee_collection: "Fee Collection",
        search_by: "Search By:",
        admission_no: "Admission No.",
        fee_code: "Fee Code",
        collection_date: "Collection Date",
        payment_mode: "Payment Mode",
        by_cash: "By Cash",
        by_cheque: "By Cheque",
        online_payment: "Online Payment",
        by_draft: "By Draft",
        by_pos: "By POS",
        by_neft: "By NEFT",
        fee_register_report: "Fee Register Report",
        fee_collection_report: "Fee Collection Report",
        based_on: "Based On",
        daily: "Daily",
        monthly: "Monthly",
        date: "Date",
        select_date: "Select Date",
        mode_of_payment: "Mode of Payment",
        deposited_at: "Deposited At",
        fee_receipt_report: "Fee Receipt Report",
        concession_report: "Concession Report",
        show_late_fee_discount: "Show Late Fee Discount",
        fee_defaulter_report: "Fee Defaulter Report",
      },
    },
    hi: {
      translation: {
        Edit: "संपादन करना",
        school_details: "स्कूल विवरण",
        school_name: "स्कूल का नाम",
        school_code: "स्कूल कोड",
        fee_category: "शुल्क श्रेणी",
        create_fee_category: "शुल्क श्रेणी बनाएं",
        edit_fee_category: "शुल्क श्रेणी संपादित करें",
        existing_particulars: "मौजूदा विवरण",
        add_new_particulars: "नए विवरण जोड़ें",
        description: "विवरण",
        particular_name: "विशेष नाम",
        back: "वापस",
        save: "सहेजें",
        fee_amount_particular: "शुल्क राशि विशेष",
        create_fee_amount_particular: "शुल्क राशि विशेष बनाएं",
        category_name: "श्रेणी का नाम",
        fee_particular: "शुल्क विशेष",
        academic_year: "शैक्षणिक वर्ष",
        account: "खाता",
        amount: "राशि",
        select_class_sections: "कक्षा और अनुभाग चुनें",
        select_student_category: "छात्र श्रेणी चुनें",
        class: "कक्षा",
        section: "अनुभाग",
        select_students: "छात्र चुनें",
        fee_concession: "शुल्क रियायत",
        create_fee_concession: "शुल्क रियायत बनाएं",
        show_data: "डेटा दिखाएं",
        manage_scheduled_concession: "निर्धारित रियायत प्रबंधित करें",
        concession_type: "रियायत प्रकार *",
        concession_name: "रियायत का नाम",
        is_percent: "प्रतिशत है",
        concession_amount: "रियायत राशि",
        select_student: "छात्र चुनें",
        select_wings: "विंग्स चुनें",
        student_category: "छात्र श्रेणी",
        late_fee: "विलंब शुल्क",
        new_late_fee: "नया विलंब शुल्क",
        create_late_fee: "विलंब शुल्क बनाएं",
        fine_name: "जुर्माना नाम",
        late_fee_calculation_type: "विलंब शुल्क गणना प्रकार",
        days_after_due_date: "देय तिथि के बाद दिन",
        manage_late_fee: "विलंब शुल्क प्रबंधित करें",
        fee_schedule: "शुल्क अनुसूची",
        create_fee_schedule: "शुल्क अनुसूची बनाएं",
        excess_fee: "अतिरिक्त शुल्क",
        account_name: "खाता नाम",
        fine_particular: "जुर्माना विशेष",
        create_new_fine_particular: "नया जुर्माना विशेष बनाएं",
        create_fine_particular: "जुर्माना विशेष बनाएं",
        student: "छात्र",
        excess_amount: "अतिरिक्त राशि",
        select_payment_status: "भुगतान स्थिति चुनें",
        add_amount: "राशि जोड़ें",
        total_amount: "कुल राशि",
        fee_collection_name: "शुल्क संग्रह नाम",
        start_date: "प्रारंभ तिथि",
        end_date: "समाप्ति तिथि",
        due_date: "देय तिथि",
        late_fine: "विलंब जुर्माना",
        is_applicable: "लागू है",
        fee_collection: "शुल्क संग्रह",
        search_by: "द्वारा खोजें:",
        admission_no: "प्रवेश संख्या",
        fee_code: "शुल्क कोड",
        collection_date: "संग्रह तिथि",
        payment_mode: "भुगतान का तरीका",
        by_cash: "नकद द्वारा",
        by_cheque: "चेक द्वारा",
        online_payment: "ऑनलाइन भुगतान",
        by_draft: "ड्राफ्ट द्वारा",
        by_pos: "पीओएस द्वारा",
        by_neft: "एनईएफटी द्वारा",
        fee_register_report: "शुल्क रजिस्टर रिपोर्ट",
        fee_collection_report: "शुल्क संग्रह रिपोर्ट",
        based_on: "आधारित",
        daily: "दैनिक",
        monthly: "मासिक",
        date: "तिथि",
        select_date: "तिथि चुनें",
        mode_of_payment: "भुगतान का तरीका",
        deposited_at: "जमा किया गया स्थान",
        fee_receipt_report: "शुल्क रसीद रिपोर्ट",
        concession_report: "रियायत रिपोर्ट",
        show_late_fee_discount: "विलंब शुल्क छूट दिखाएं",
        fee_defaulter_report: "शुल्क बकायेदार रिपोर्ट",
      },
    },
  },
  fallbackLng: "hi",
  lng: "hi",
  interpolation: {
    escapeValue: false, // React already escapes the values, so no need for additional escaping
  },
});

export default i18n;
